server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = /nicole/remoteEntry.js {
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  location /nicole/assets/ {
    try_files $uri =404;
  }

  location /nicole/ {
    try_files $uri =404;
  }

  location / {
    return 404;
  }
}
