apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.appServiceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.appServiceName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.appServiceName" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.appPort }}
          env:
            - name: DATABASE_URL
              value: {{ include "app.databaseURL" . | quote }}
            - name: NATS_URL
              value: "nats://{{ include "app.natsServiceName" . }}:{{ .Values.nats.port }}"
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: {{ .Values.googleOAuth.clientID | quote }}
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              value: {{ .Values.googleOAuth.clientSecret | quote }}
            - name: GOOGLE_OAUTH_PUBLIC_BASE_URL
              value: {{ .Values.googleOAuth.publicBaseURL | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.appPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.appPort }}
