apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.postgresServiceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.postgresServiceName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.postgresServiceName" . }}
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
