apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.webTodoServiceName" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.webTodoServiceName" . }}
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: 80
