apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.webTodoServiceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.webTodoServiceName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.webTodoServiceName" . }}
    spec:
      containers:
        - name: web-todo
          image: "{{ .Values.images.webTodo.repository }}:{{ .Values.images.webTodo.tag }}"
          imagePullPolicy: {{ .Values.images.webTodo.pullPolicy }}
          ports:
            - containerPort: 80
