apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.appServiceName" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.appServiceName" . }}
  ports:
    - name: http
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
