apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.natsServiceName" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.natsServiceName" . }}
  ports:
    - name: nats
      port: {{ .Values.nats.port }}
      targetPort: {{ .Values.nats.port }}
